package com.btpnsyariah.autoapproval;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class output implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.String autoReject;

	private java.lang.String rejectCode;

	private java.lang.String deviationCode;

	private java.lang.String nosValue;

	public output() {
	}

	public java.lang.String getAutoReject() {
		return this.autoReject;
	}

	public void setAutoReject(java.lang.String autoReject) {
		this.autoReject = autoReject;
	}

	public java.lang.String getRejectCode() {
		return this.rejectCode;
	}

	public void setRejectCode(java.lang.String rejectCode) {
		this.rejectCode = rejectCode;
	}

	public java.lang.String getDeviationCode() {
		return this.deviationCode;
	}

	public void setDeviationCode(java.lang.String deviationCode) {
		this.deviationCode = deviationCode;
	}

	public java.lang.String getNosValue() {
		return this.nosValue;
	}

	public void setNosValue(java.lang.String nosValue) {
		this.nosValue = nosValue;
	}

	public output(java.lang.String autoReject, java.lang.String rejectCode,
			java.lang.String deviationCode, java.lang.String nosValue) {
		this.autoReject = autoReject;
		this.rejectCode = rejectCode;
		this.deviationCode = deviationCode;
		this.nosValue = nosValue;
	}

}