package com.btpnsyariah.autoapproval;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class response implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public response() {
    }




}