package com.btpnsyariah.autoapproval;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class testmodel implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.util.Date birthDate;

	public testmodel() {
	}

	public java.util.Date getBirthDate() {
		return this.birthDate;
	}

	public void setBirthDate(java.util.Date birthDate) {
		this.birthDate = birthDate;
	}

	public testmodel(java.util.Date birthDate) {
		this.birthDate = birthDate;
	}

}