package com.btpnsyariah.autoapproval;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class testmodel implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.util.Date date;

	public testmodel() {
	}

	public java.util.Date getDate() {
		return this.date;
	}

	public void setDate(java.util.Date date) {
		this.date = date;
	}

	public testmodel(java.util.Date date) {
		this.date = date;
	}

}